### ISSUE TITLE
My Win11 shows the msi has a virus[BUG]

### ISSUE THREAD

**Issue by Jelga01** [mi0bot/OpenHPSDR-Thetis#76]
My Win11 shows the msi has virus detected

**Comment by DH1KLM** [comment]
Most likely a false positive reading from defender etc.
This also happens to me sometimes after successfully compiling Thetis. In my case, the freshly compiled Thetis.exe is displayed as infected, even though my system is 100% virus-free.

This problem is known.
It just happens from time to time.

Explanation from Richie here: https://community.apache-labs.com/viewtopic.php?f=9&t=4771&p=26932#p26932

**Comment by Jelga01** [comment]
I don't think this is a false positive. I have attached a screenshot. It identifies the trojan script.
My apologies for not giving more detail earlier.

See Attached:

Later,

Jim
________________________________

**Comment by Jelga01** [comment]
I downloaded the file on a win10 machine, then moved it to my win11 machine.
I then ran a virus scan on that individual file. It found no threats.

Now I am completely confused:)

Later,

Jim
________________________________

**Comment by DH1KLM** [comment]
Here is a scan of Richie's current Thetis version:
https://www.virustotal.com/gui/url/02e4a5157da776c521f5ea2996fb933cbac0e8677d28db5e9e8fb61ef5d68cfb?nocache=1

And here again for comparison is Reid's Thetis version:
https://www.virustotal.com/gui/url/4fad0ad91e1ae9a083913ab01fe2a10eb34e3167b9bfbcd67da41fc506987b69?nocache=1

The same result for both versions. Only Antiy-AVL thinks the file is malicious

I think if it really is a virus or trojan, many OMs would have reported it. I think it's a false positive.

And again: "The trouble is, these days you get some odd byte order in a legit file and boom, it becomes flagged as a virus, a false positive. Price we have to pay I guess for non-signed installer."
